/*
 * Generic file load/save routines
 *
 * create a pointer to smud_file:
 *      smud_file *myfile;
 *
 * read the file into the variale (memory is allocated for you):
 *      myfile = read_file("filename");
 *
 * Get entry by tag and vnum combination:
 *      char *getval(myfile,vnum,"tagname");
 *
 * Number of vnums in the file:
 *      myfile->vnumcount   (short)
 *
 * Array of vnums:
 *      myfile->vnumlist[x] (short)
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#define SECTION_ITEMS 30
#define SECTION_MAX 1000

typedef struct file_entry_s {
	short vnum;
	char *tag;
	char *data;
} file_entry;

typedef struct smud_file_s {
	short fileptr;
	short lines;
	file_entry data[SECTION_ITEMS*SECTION_MAX];
	short vnumlist[SECTION_MAX];
	short vnumcount;
} smud_file;

void trim(char *text)
{
	char *ptr;
	while((*text==' ') || (*text=='\t'))
	{
		for(ptr=text; ptr<text+strlen(text); ptr++)
		{
			*ptr = *(ptr+1);
		}
	}
	for(ptr=text+strlen(text); (*ptr<=' ') && (ptr>text) ; ptr--)
		*ptr='\0';
}

void lfreplace(char *text)
{
	char *work = strdup(text);
	char *tok;
	bzero(text,strlen(work));

	tok=work;
	while(*tok!=0)
	{
		if(*tok=='\\' && *(tok+1)=='n')
		{
			*text = '\n';
			tok++;
		} else {
			*text = *tok;
		}
		tok++;
		text++;
	}
	free(work);
}

void lowercase(char *text)
{
	char *ptr;
	for(ptr=text; *ptr!='\000'; ptr++)
		*ptr=tolower(*ptr);
}

smud_file *read_file(char *name)
{
	FILE *fd;
	short in_set=0;
//	char *buffer = malloc(16384);
	char buffer[16384];
	short vnum;
	char tag[20];
	char data[16384];
	short count;
	smud_file *myfile = malloc(sizeof(smud_file));
	
	myfile->vnumcount=0;
	myfile->lines=0;

	fd = fopen(name,"r");
	if(!fd) return myfile;
	while(fgets(buffer,16384,fd))
	{
		trim(buffer);
		if(*buffer != '#')
		{
			if(sscanf(buffer,"%s",tag)==1)
			{
				lowercase(tag);
				bzero(data,16384);
				for(count=strlen(tag); count<strlen(buffer); count++)
					data[count-strlen(tag)] = *(buffer+count+1);		
			}

			if(tag[0]=='}')
			{
				in_set = 0;
			}

			if(in_set==1)
			{
				lfreplace(data);
				myfile->data[myfile->lines].vnum = vnum;
				myfile->data[myfile->lines].tag = strdup(tag);
				myfile->data[myfile->lines].data = strdup(data);
				myfile->lines++;
			}

			if(data[0]=='{')
			{
				in_set=1;
				vnum = atoi(tag);
				myfile->vnumlist[myfile->vnumcount++] = vnum;
			}
		}
	}
	fclose(fd);
	return myfile;
}

char *getval(smud_file *myfile, short vnum, char *tag)
{
	short i;
	char *val=NULL;
	
	if(vnum>0)
	{
		val = getval(myfile,0,tag);
	}
	for(i=0; i<myfile->lines; i++)
	{
		if((vnum==myfile->data[i].vnum) && (!strcasecmp(tag,myfile->data[i].tag)))
		{
			val = myfile->data[i].data;
			trim(val);
			return val;
		}
	}
	if(val) return val;
	return "";
}

smud_file *new_file()
{
	smud_file *myfile;
	myfile = malloc(sizeof(smud_file));
	myfile->lines=0;
	myfile->vnumcount=0;
	return myfile;
}

void add_entry(smud_file *myfile, short vnum, char *tag, char *data)
{
	short i;
	for(i=0; i<myfile->lines; i++)
	{
		if((myfile->data[i].vnum==vnum) && (!strcasecmp(myfile->data[i].tag,tag)))
		{
			free(myfile->data[i].data);
			myfile->data[i].data = strdup(data);
			return;
		}
	}
	myfile->data[myfile->lines].vnum = vnum;
	myfile->data[myfile->lines].tag = strdup(tag);
	myfile->data[myfile->lines].data = strdup(data);
	myfile->lines++;
	for(i=0; i<myfile->vnumcount; i++)
	{
		if(myfile->vnumlist[i]==vnum)
			return;
	}
	myfile->vnumlist[myfile->vnumcount]=vnum;
	myfile->vnumcount++;
	return;
}

void write_file(smud_file *myfile, char *filename)
{
	FILE *fd;
	short i;
	short j;

	fd = fopen(filename,"w");
	fprintf(fd,"%s\n","# File auto generated by smud.\n");
	for(i=0; i<myfile->vnumcount; i++)
	{
		fprintf(fd,"%d {\n",myfile->vnumlist[i]);
		for(j=0; j<myfile->lines; j++)
		{
			if(myfile->data[j].vnum==myfile->vnumlist[i])
			{
				char *temp,*tok;
				int l;
				temp = malloc((strlen(myfile->data[j].data)*2)+1);
				bzero(temp,(strlen(myfile->data[j].data)*2)+1);
				tok=myfile->data[j].data;
				while(*tok)
				{
					if(*tok=='\n')
					{
						temp = strcat(temp,"\\n");
					} else {
						l=strlen(temp);
						temp[l]=*tok;
						temp[l+1]='\0';
					}
					tok++;
				}
				fprintf(fd,"	%s %s\n",myfile->data[j].tag,temp);
				free(temp);
			}
		}
		fprintf(fd,"}\n\n");
	}
	fclose(fd);
}

void freefile(smud_file *myfile)
{
	short i;
	for(i=0; i<myfile->lines; i++)
	{
		free(myfile->data[i].tag);
		free(myfile->data[i].data);
	}
	free(myfile);
}

