sys_command comlist[]={
{"quaff", NORM,drink},
{"look",NORM,look},
{"north",NORM,move_north}, /* move(uid,0,1); */
{"south",NORM,move_south}, /* move(uid,2,1); */
{"east",NORM,move_east}, /* move(uid,1,1); */
{"west",NORM,move_west}, /* move(uid,3,1); */
{"ne",NORM,move_ne}, /* move(uid,4,1); */
{"se",NORM,move_se}, /* move(uid,6,1); */
{"sw",NORM,move_sw}, /* move(uid,7,1); */
{"nw",NORM,move_nw}, /* move(uid,5,1); */
{"up",NORM,move_up}, /* move(uid,8,1); */
{"finger",NORM,finger},
{"down",NORM,move_down}, /* move(uid,9,1); */
{"say",NORM,say},
{"score",NORM,score},
{"consider",NORM,consider},
{"kill",NORM,killx},
{"flee",NORM,flee},
{"who",NORM,who},
{"help",NORM,help},
{"inventory",NORM,inventory},
{"take",NORM,take},
{"drop",NORM,xdrop},
{"exits",NORM,exits},
{"hold",NORM,hold},
{"examine",NORM,examine},
{"recall",NORM,recall},
{"chat",NORM,chat},
{"chemote",NORM,chem},
{"shutdown",IMM,xshutdown},
{"set",NORM,xset},
{"time",NORM,xtime},
{"tell",NORM,tell},
{"remote",NORM,remote},
{"locate",CARETAKER,locate},
{"goto",GUIDE,xgoto},
{"bug",NORM,bug},
{"typo",NORM,typo},
{"idea",NORM,idea},
{"withdraw",NORM,withdraw},
{"deposit",NORM,deposit},
{"balance",NORM,balance},
{"weather",NORM,xweather},
{"ask",NORM,ask},
{"emote",NORM,emote},
{"idle",NORM,xidle},
{"afk",NORM,afk},
{"commands",NORM,commands},
{"sleep",NORM,xsleep},
{"rest",NORM,xrest},
{"stand",NORM,xwake},
{"wake",NORM,xwake},
{"news",NORM,news},
{"drivel",NORM,driv},
{"dremote",NORM,drem},
{"question",NORM,question},
{"answer",NORM,answer},
{"qemote",NORM,qemote},
{"aemote",NORM,aemote},
{"follow",NORM,follow},
{"group",NORM,group},
{"gsay",NORM,gsay},
{"gemote",NORM,gemote},
{"areas",NORM,xareas},
{"info",IMM,info},
{"makehome",IMM,makehome},
{"home",NORM,home},
{"leave",NORM,leave},
{"visit",NORM,visit},
{"wear",NORM,wear},
{"wield",NORM,wear},
{"remove",NORM,xremove},
{"show",NORM,xshow},
{"noisy",NORM,dolist_noisy}, /* dolist(uid,lNOISY); */
{"ignore",NORM,dolist_ignore}, /* dolist(uid,lIGNORE); */
{"inform",NORM,dolist_inform}, /* dolist(uid,lINFORM); */
{"grabme",NORM,dolist_grabme}, /* dolist(uid,lGRABME); */
{"friend",NORM,dolist_friend}, /* dolist(uid,lFRIEND); */
{"bar",NORM,dolist_bar}, /* dolist(uid,lBAR); */
{"invite",NORM,dolist_invite}, /* dolist(uid,lINVITE); */
{"beep",NORM,dolist_beep}, /* dolist(uid,lBEEP); */
{"block",NORM,dolist_block}, /* dolist(uid,lBLOCK); */
{"find",NORM,dolist_find}, /* dolist(uid,lFIND); */
{"key",NORM,dolist_key}, /* dolist(uid,lKEY); */
{"visitable",NORM,visitable}, 
{"unvisitable",NORM,unvisitable},
{"use",NORM,use},
{"wimpy",NORM,wimpy},
{"list",NORM,list},
{"value",NORM,value},
{"buy",NORM,buy},
{"sell",NORM,sell},
{"gtell",NORM,gsay},
{"immon",NORM,immon},
{"immoff",NORM+1,immoff},
{"open",NORM,xopen},
{"close",NORM,xclose},
{"affects",NORM,affects},
{"drink",NORM,drink},
{"join",NORM,join},
{"guilds",NORM,xguilds},
{"mpurge",IMM,mpurge},
{"tf",NORM,tf},
{"rf",NORM,rf},
{"give",NORM,give},
{"givecash",IMM,givecash},
{"get",NORM,take},
{"quit",NORM,quit1},
{"save",NORM,xsave},
{"reboot",IMM,mud_reboot},
{"equipment",NORM,inventory},
{"fwho",NORM,fwho},
{"mrefresh",IMM,mrefresh},
{"rrefresh",IMM,rrefresh},
{"orefresh",IMM,orefresh},
{"train",NORM,train},
{"sacrifice",NORM,sacrifice},
{"skills",NORM,skills},
{"practice",NORM,practice},
{"summon",IMM,summon},
{"boot",IMM,boot},
{"cunt",IMM,cunt},
{"giveprac",IMM,giveprac},
{"testedit",IMM,testedit},
{"roomedit",IMM,editroom},
{"newsedit",IMM,newsedit},
{"resetnews",IMM,resetnews},
{"criminal",NORM,criminal},
{"league",NORM,league},
{"ginfo",NORM,ginfo},
{"finance",NORM,finance},
{"nuke",IMM,nuke},
{"prompt",NORM,xprompt},
{"cprompt",NORM,xcprompt},
{"watch",IMM,watch},
{"advance",IMM,advance},
{"editsign",IMM,editsign},
{"removesign",IMM,removesign},
{"debates",NORM,cdebate},
{"enter",NORM,enter},
{"recite",NORM,Slread},
{"mail",NORM,mail},
{"showlist",NORM,showlist},
{"post",NORM,post},
{"unwrap",NORM,unwrap},
{"arm",NORM,arm},
{"shortcuts",NORM,shortcuts},
{"oload",IMM,oload},
{"build",NORM,build},
{"report",NORM,report},
{"xyzzy",NORM,xyzzy},

// skills... lets keep them together for now
{"retreat",NORM,Sretreat},
{"disarm",NORM,Sdisarm},
{"rescue",NORM,Srescue},
{"kick",NORM,Skick},
{"strangle",NORM,Sstrangle},
{"punch",NORM,Spunch},
{"headbutt",NORM,Sheadbutt},
{"charge",NORM,Scharge},
{"burn",NORM,Sburn},
{"stab",NORM,Sstab},
{"read",NORM,Sqread},
{"throw",NORM,Sthrow},
{"sneak",NORM,Ssneak},
{"hide",NORM,Shide},
{"pickpocket",NORM,Spickpocket},
{"*",-1,(void *)0}
};
